server:
  port: 38111

spring:
  application:
    name: backend-payment

  cloud:
    openfeign:
      client:
        config:
          RemoteLectureService:
            url: http://localhost:38106

  datasource:
    url: jdbc:postgresql://localhost:38121/payment?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:381233
    listener:
      ack-mode: manual_immediate
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      auto-offset-reset: latest
      max-poll-records: 10
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  data:
    redis:
      host: localhost
      port: 6379
      database: 14

kakao:
  baseUrl: https://open-api.kakaopay.com/online/v1/payment
  connectTimeout: 5000
  readTimeout: 5000
  cid: "TC0ONETIME"
  approvalUrl: "http://localhost:5173/success"
  failUrl: "http://localhost:5173/fail"
  cancelUrl: "http://localhost:5173/cancel"
  taxFreeAmount: 0
  vatAmount: 0
  secret: ${KAKAO_SECRET}
  partnerOrderId: "hello"
  partnerUserId: "hello"
